apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "alert_rules.yml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)

      - job_name: 'pet-project-api'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - pet-project
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: pet-project-api
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http

  alert_rules.yml: |
    groups:
      - name: pet-project-alerts
        rules:
          - alert: PetProjectDown
            expr: up{job="pet-project-api"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Pet Project API is down"
              description: "Pet Project API has been down for more than 1 minute"

          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.02
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High error rate detected"
              description: "Error rate is above 2% for more than 2 minutes"

          - alert: HighCPUUsage
            expr: rate(container_cpu_usage_seconds_total[5m]) > 0.5
            for: 3m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage detected"
              description: "CPU usage is above 50% for more than 3 minutes"
